### ISSUE TITLE
Pictures displayed by not downloading

### ISSUE THREAD

**Issue by bllittle** [helgasoft/Chrome-Ext-Gvoice#1]
Hi,

Thanks for this extension. I just loaded it as instructed and while it does appear to retrieve photos in a conversation thread, when clicking a picture in the list nothing appears to happen. I tried right clicking to see if a context menu would appear and it appears to be the standard Chrome photo context menu. Opening a photo in a new tab appears to open the thumbnail version. 

I'm using Chrome 91.0.4472.124 (Official Build) (64-bit) on a Windows 10, 64-bit laptop. 

Thanks,
Bruce

**Comment by helgasoft** [comment]
Bruce, 
Clicking on a thumbnail photo from the extension dropdown list should open the **Downloads toolbar** (ctrl+J) on Chrome's window bottom. There one should see the name of the photo being downloaded.

It still works the same, as of today, with Chrome Version 96.0.4664.93 (Official Build) (64-bit), Windows 10.
